-- Purpose:

-- NiFi will poll this table

-- Source of the streaming pipeline.

CREATE TABLE RAW_TRANSACTIONS (
    TRANSACTION_ID VARCHAR2(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR2(50) ,
    AMOUNT NUMBER(12, 2),
    CURRENCY VARCHAR2(10),
    MERCHANT_ID VARCHAR2(50),
    MERCHANT_CATEGORY VARCHAR2(100),
    TRANSACTION_TYPE VARCHAR2(20),
    TRANSACTION_TIME TIMESTAMP,
    COUNTRY VARCHAR2(20),
    DEVICE_ID VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Purpose:

-- Stores feature-engineered data.

CREATE TABLE ENRICHED_TRANSACTIONS (
    TRANSACTION_ID VARCHAR2(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR2(50) ,
    AMOUNT NUMBER(12, 2),
    HOUR_OF_DAY NUMBER,
    IS_HIGH_AMOUNT CHAR(1),
    GEO_RISK_SCORE NUMBER,
    CREATED_AT TIMESTAMP 
);

-- Fraud scoring service stores results here.

CREATE TABLE FRAUD_RESULTS (
      TRANSACTION_ID VARCHAR2(50) PRIMARY KEY,
      FRAUD_SCORE NUMBER(5, 2),
      RISK_LEVEL VARCHAR2(20),
      DECISION VARCHAR2(20),
      CREATED_AT TIMESTAMP

);

-- Tracks distributed transaction lifecycle.
-- Maintains Saga orchestration state.

CREATE TABLE SAGA_STATE (
    SAGA_ID VARCHAR2(50) PRIMARY kEY,
    TRANSACTION_ID VARCHAR2(50),
    CURRENT_STEP VARCHAR2(50),
    STATUS VARCHAR2(20),
    UPDATED_AT TIMESTAMP
);


-- Financial accounting.

CREATE TABLE LEDGER_ENTRIES (
    ENTRY_ID VARCHAR2(50) PRIMARY KEY,
    TRANSACTION_ID VARCHAR2(50),
    CUSTOMER_ID VARCHAR2(50),
    AMOUNT NUMBER(12, 2),
    ENTRY_TYPE VARCHAR2(20),
    CREATED_AT TIMESTAMP
);

-- For traceability.

CREATE TABLE AUDIT_LOG (
    LOG_ID VARCHAR2(50) PRIMARY KEY,
    TABLE_NAME VARCHAR2(50),
    ACTION VARCHAR2(50),
    USER_NAME VARCHAR2(50),
    LOG_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

