-- Fraud analytics queries often filter by time or score.

-- Indexes reduce scan time.

CREATE INDEX IDX_TXN_CUSTOMER
ON RAW_TRANSACTIONS (CUSTOMER_ID);

CREATE INDEX IDX_ENRICHED_TIME
ON ENRICHED_TRANSACTIONS (CREATED_AT);

CREATE INDEX IDX_FRAUD_SCORE
ON FRAUD_RESULTS (FRAUD_SCORE);

