-- We are using partitions when we working with huge tables

CREATE TABLE TXN_HISTORY (
    TRANSACTION_ID VARCHAR2(50),
    CUSTOMER_ID VARCHAR2(50),
    AMOUNT NUMBER(12, 2),
    TXN_TIME DATE
)

PARTITION BY RANGE (TXN_TIME)
(
    PARTITION p2025 VALUES LESS THAN(TO_DATE('01-JAN-2026', 'DD-MON-YYYY')),
    PARTITION p2026 VALUES LESS THAN(TO_DATE('01-JAN-2027', 'DD-MON-YYYY'))
)