-- Automatically logs changes.
-- Compliance auditing.

CREATE OR REPLACE TRIGGER RAW_TXN_AUDIT
AFTER INSERT ON RAW_TRANSACTIONS 
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG (TABLE_NAME, ACTION, USER_NAME)
    VALUES ('RAW_TRANSACTIONS', 'INSERT', USER);
END;
/